name: deploy

on:
    push:
        branches:
            - main

jobs:
    publish_docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: yarn

            - name: Build website
              run: yarn build

            - uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
